### ISSUE TITLE
Broken link on string resources item: Shawarma

### ISSUE THREAD

**Issue by salvatop** [udacity/sandwich-club-starter-code#21]
File : sandwich-club-starter-code/app/src/main/res/values/strings.xml

Item name: Shawarma

Broken link: https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Shawarmafood.jpg/800px-Shawarmafood.jpg

Working link: https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/D%C3%B6ner_kebap.jpg/800px-D%C3%B6ner_kebap.jpg

**Comment by johnshea** [comment]
Fixed.
